### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by thsanki** [M1n007/igtools#5]
![Screenshot_2019-12-31-12-54-33-13_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/59386036/71613465-b8aeaf00-2bcc-11ea-809e-0959dd5878ae.png)
Please solve... please reply please

**Comment by ishandutta2007** [comment]
Same error for me.
@thsanki btw how do you run nodejs on mobile ?

**Comment by M1n007** [comment]
I haven't maintained this tools again for a long time because I was busy, u can contribute.
