### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Devshimitsu** [M1n007/igtools#8]
FetchError: invalid json response body at https://www.instagram.com/accounts/web_create_ajax/ reason: Unexpected token B in JSON at position 0
    at /data/data/com.termux/files/home/igtools/node_modules/node-fetch/lib/index.js:241:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  type: 'invalid-json'
}

**Comment by alaattinyilmaz** [comment]
Same problem, is there any solution?

**Comment by M1n007** [comment]
I haven't maintained this tools again for a long time because I was busy, u can contribute.
